apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: foo-pvc
  namespace: hcp
spec:
  storageClassName: hostpath # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: foo-pv
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi