apiVersion: v1
kind: Service
metadata:
  name: uni-sample
  namespace: hcp
  labels:
    name: uni-sample
spec:
  type: NodePort
  ports:
  - port: 2052
    targetPort: 2052
    # nodePort: 32051
    protocol: TCP
  selector:
    name: uni-sameple
