apiVersion: apps/v1
kind: Deployment
metadata:
  name: hcp-apiserver
  namespace: hcp
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hcp-apiserver
  template:
    metadata:
      labels:
        name: hcp-apiserver
    spec:
      serviceAccountName: hcp-apiserver
      imagePullSecrets:
        - name: regcred
      containers:
        - name: hcp-apiserver
          image: ketidevit2/hcp-apiserver:v0.0.2
          command:
          - hcp-apiserver
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              #value: ""
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: INFLUX_IP
              value: "10.0.5.83"
            - name: INFLUX_PORT
              value: "31051"
            - name: INFLUX_USERNAME
              value: "root"
            - name: INFLUX_PASSWORD
              value: "root"
            - name: OPERATOR_NAME
              value: "hcp-apiserver"
          volumeMounts:
          - name: awsconfig 
            mountPath: /root/.aws          
          - name: aksconfig 
            mountPath: /root/.azure 
          - name: gkeconfig 
            mountPath: /root/.google
          ports:
          - containerPort: 8080
            name: http
      volumes:
      - name: awsconfig
        persistentVolumeClaim:
          claimName: pvc-aws-config
      - name: aksconfig
        persistentVolumeClaim:
          claimName: pvc-aks-config
      - name: gkeconfig
        persistentVolumeClaim:
          claimName: pvc-gke-config
      tolerations:
        - key: node.kubernetes.io/not-ready
          effect: NoExecute
          tolerationSeconds: 0
        - key: node.kubernetes.io/unreachable
          effect: NoExecute
          tolerationSeconds: 0
