apiVersion: v1
kind: Service
metadata:
  namespace: hcp
  name: hcp-apiserver
spec:
  type: ClusterIP
  clusterIP: 10.96.0.2
  selector:
    name: hcp-apiserver
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080