apiVersion: v1
kind: Service
metadata:
  name: hcp-apiserver
  namespace: hcp
spec:
  selector:
    name: hcp-apiserver
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31635
    protocol: TCP
  type: LoadBalancer

