apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-kubeconfig
  labels:
    app: kube-config
spec:
  capacity:
    storage: 2Gi
  storageClassName: cluster-manager
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  # nfs:
  #   path: /root/.kube
  #   server: "10.0.5.83"
  #   readOnly: false
  local:
    path: "/var/lib/analytic-engine-pv" 
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - hcp-worker2
  
