apiVersion: v1
kind: Service
metadata:
  name: hcp-analytic-engine
  namespace: hcp
spec:
  selector:
    name: hcp-analytic-engine
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31653
  type: NodePort
