apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: hcppolicies.hcp.crd.com
spec:
  group: hcp.crd.com
  version: v1alpha1
  names:
    kind: HCPPolicy
    listKind: HCPPolicyList
    plural: hcppolicies
    singular: hcppolicy
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          type: object
        status:
          type: object
  versions:
  - name: v1alpha1
    served: true
    storage: true




