apiVersion: hcp.k8s.io/v1alpha1
kind: HCPPolicy
metadata:
  name: example-hcppolicy
  namespace: hcp
spec:
  template:
    spec:
      targetController:
        kind: HCPHybridAutoScaler
      policies:
        - type: Mode
          value:
            - Unequal
  rangeOfApplication: All
  policyStatus: Enabled
