apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: hcppolicies.hcp.crd.com
spec:
  group: hcp.crd.com
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              template:
                type: object
                x-kubernetes-preserve-unknown-fields: true
              rangeOfApplication: 
                type: string
              policyStatus:
                 type: string
                 enum: 
                 - Enabled
                 - Disabled
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
  scope: Namespaced
  names:
    kind: HCPPolicy
    listKind: HCPPolicyList
    plural: hcppolicies
    singular: hcppolicy
