kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hcp-analytic-engine-rolebinding
  namespace: hcp
subjects:
- kind: ServiceAccount
  name: hcp-analytic-engine-sa
  namespace: hcp
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
