apiVersion: v1
kind: Service
metadata:
  name: hcp-metric-collector
  namespace: hcp
  labels:
    name: hcp-metric-collector
spec:
  type: NodePort
  ports:
  - port: 2052
    targetPort: 2052
    # nodePort: 32051
    protocol: TCP
  selector:
    name: hcp-metric-collector
