apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: hcphybridautoscalers.hcp.crd.com
spec:
  group: hcp.crd.com
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              mode:
                type: string
              targetCluster:
                type: string
              warningCount:
                type: integer
              scalingOptions:
                type: object
                properties:
                  hpaTemplate:
                    x-kubernetes-preserve-unknown-fields: true
                    type: object
                  vpaTemplate:
                    x-kubernetes-preserve-unknown-fields: true
                    type: object
          status:
            type: object
            properties:
              resourceStatus:
                type: string
                enum:
                - CREATED
                - WAITING
                - TERMINATING
                - DONE
              lastSpec:
                x-kubernetes-preserve-unknown-fields: true
                type: object
  scope: Namespaced 
  names:
    kind: HCPHybridAutoScaler
    listKind: HCPHybridAutoScalerList
    plural: hcphybridautoscalers
    singular: hcphybridautoscaler
    shortNames:
    - hcphas
    

