
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-kubeconfig
  namespace: hcp
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: hostpath
  selector:
    matchLabels:
      app: kube-config
