apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-influxdb
spec:
  capacity:
    storage: 2Gi
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /home/nfs/pv/influxdb
    server: "10.0.5.83"
    readOnly: false
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-influxdb2
spec:
  capacity:
    storage: 2Gi
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /home/nfs/pv/influxdb
    server: "10.0.5.83"
    readOnly: false
