apiVersion: v1
kind: PersistentVolume
metadata:
  name: foo-pv
spec:
  storageClassName: hostpath
  claimRef:
    name: foo-pvc
    namespace: hcp
  accessModes:
    - ReadWriteMany
  hostPath:
     path: "/mnt/data"
  capacity:
    storage: 10Gi