apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-app
spec:
  selector:
    matchLabels:
      app: nginx-app
  replicas: 2
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx-app
    spec:
      nodeName: keti-test-nodepool-w-1hp9
      containers:
      - name: nginx-pod
        image: nginx:1.14 
