apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    app: nginx-app
spec:
  nodeName: ip-172-31-36-141.ap-northeast-2.compute.internal
  selector:
    matchLabels:
      app: nginx-app
  replicas: 2
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx-pod
        image: nginx:1.14 
