apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hcp-deployment-controller
  namespace: hcp
subjects:
- kind: ServiceAccount
  name: hcp-deployment-controller
  namespace: hcp
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io