apiVersion: v1
kind: Service
metadata:
  namespace: hcp
  name: hcp-apiserver
spec:
  type: LoadBalancer
  clusterIP: 10.96.0.2
  selector:
    name: hcp-apiserver
  ports:
    - protocol: TCP
      name: default
      port: 8080
      targetPort: 8080
    - protocol: TCP
      name: https
      port: 443
      targetPort: 443
    - protocol: TCP
      name: http
      port: 80
      targetPort: 80