apiVersion: v1
kind: Service
metadata:
  name: hcp-has-controller
  labels:
    app: hcp-has-controller
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8086
    protocol: TCP
    name: http
  selector:
    app: hcp-has-controller