apiVersion: apps/v1
kind: Deployment
metadata:
  name: hcp-deployment-controller
  namespace: hcp
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hcp-deployment-controller
  template:
    metadata:
      labels:
        name: hcp-deployment-controller
    spec:
      serviceAccountName: hcp-deployment-controller
      imagePullSecrets:
      - name: regcred
      containers:
      - name: hcp-deployment-controller
        image: ketidevit2/hcp-deployment-controller:v0.0.2
        command:
        - hcp-deployment-controller
        imagePullPolicy: Always
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: "hcp-deployment-controller" 
      tolerations:
      - key: node.kubernetes.io/not-ready
        effect: NoExecute
        tolerationSeconds: 0
      - key: node.kubernetes.io/unreachable
        effect: NoExecute
        tolerationSeconds: 0
      #dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 8.8.8.8       
