# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: influxdb
# spec:
#   capacity:
#     storage: 2Gi
#   storageClassName: influxdb
#   accessModes:
#     - ReadWriteMany
#   persistentVolumeReclaimPolicy: Retain
#   hostPath:
#     path: "/var/lib/influxdb"
# ---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-influxdb
spec:
  storageClassName: influxdb
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  local:
    path: "/var/lib/influxdb"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - hcp-worker2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: pv-influxdb
   namespace: hcp
spec:
   volumeName: pv-influxdb
   storageClassName: influxdb
   accessModes:
     - ReadWriteMany
   resources:
     requests:
       storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: hcp
  labels:
    component: influxdb
    app: influxdb
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  type: NodePort
  ports:
  - port: 8086
    targetPort: 8086
    nodePort: 31051
    name: server
  selector:
    component: influxdb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: hcp
  name: influxdb
  labels:
    component: influxdb
    app: influxdb
spec:
  serviceName: influxdb
  selector:
    matchLabels:
      component: influxdb
  replicas: 1
  template:
    metadata:
      name: influxdb
      labels:
        component: influxdb
        app: influxdb
    spec:
      containers:
      - name: influxdb
        image: influxdb:1.6.4
        imagePullPolicy: Always
        resources:
          limits:
            memory: 2G
          requests:
            memory: 1G
        env:
          - name: INFLUXDB_IFQL_ENABLED
            value: "true"
          - name: INFLUXDB_LOGGING_LEVEL
            value: "error"
          - name: INFLUXDB_HTTP_LOG_ENABLED
            value: "false"
        volumeMounts:
          - name: pv-influxdb
            mountPath: /var/lib/influxdb
        ports:
          - containerPort: 8086
            name: server
          - containerPort: 8082
            name: ifql
      volumes:
        - name: pv-influxdb
          persistentVolumeClaim:
            claimName: pv-influxdb
