apiVersion: v1
kind: ServiceAccount
metadata:
  name: metric-test
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: metric-test
  namespace: default
subjects:
- kind: ServiceAccount
  name: metric-test
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: metric-test
  namespace: default
  labels:
    name: metric-test
spec:
  type: LoadBalancer
  ports:
  - port: 2052
    targetPort: 2052
    nodePort: 32052
    protocol: TCP
  selector:
    name: metric-test
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: metric-test
spec:
  selector:
    matchLabels:
      name: metric-test
  template:
    metadata:
      labels:
        name: metric-test
    spec:
      serviceAccountName: metric-test
      #schedulerName: scheduler
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
      containers:
        - name: metric-test
          image: ketidevit/kmc-metric-test:v21  #54 #49
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: CLUSTER_NAME
              value: "eks-cluster"
            - name: OPERATOR_NAME
              value: "hcp-metric-collector"
          env:
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
      tolerations:
        - key: node.kubernetes.io/not-ready
          effect: NoExecute
          tolerationSeconds: 0
        - key: node.kubernetes.io/unreachable
          effect: NoExecute
          tolerationSeconds: 0

